title: Samir Paul
subtitle: Tech Blog
description: >-
  Software Engineer
keywords: >-
  About, Experience, Education, Resume, Projects, SamirPaul, SamirPaul1,
  SamirPaulb, Samir Paul NIT Durgapur, Samir Paul Website, samirpaul.in,
  samirpaul.com, samir.com, paulsamir.com, samirp.com, Samir Paul GitHub, .in,
  SamirPaul.in, Coding Profiles, Contact, Coding, Python, Problem-Solving, Data
  Structure, Algorithms, Software Engineer, Software Developer, NIT Durgapur,
  LinkedIn, GitHub, Portfolio, Website, Profile, Links, SamirPaul, SamirPaul1,
  SamirPaulb, Samir Paul, SamirPll, samirpaul1, smrpb, Samir Paul twitter,
  MACHINE LEARNING, OPENSOURCE, MYSQL, PYTHON3, LeetCode, CodeChef, HackerRank,
  GFG, competitive coding, programming, internship, SEO, projects, git, tech, 
  tech news,  github, portfolio, personal website, NIT Durgapur, National
  Institute of Technology Durgapur, IIT, West Bengal, India, software developer,
  coaching, coding, google, amazon, meta, faang, maangm, maang, project
  management, microsoft, netflix, apple, usa, seattle, blog, personal blog, tech
  article, new technology, student, B.Tech, ECE, electronics and communication
  technology, Samir Paul, SamirPaul1, samirpaul.com, samirpaul.net, samir paul
  linkedin, samirpaul, personal branding, graduation, backend, fullstack,
  development, SDE, SWE, Samir, SamirP
author: Samir Paul
language: en
timezone: Asia/Kolkata
url: https://samirpaul1.github.io/
permalink: posts/:title/
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: butterfly
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  template: ./sitemap_template.xml
  template_txt: ./sitemap_template.txt
  rel: true
  tags: true
  categories: true
feed:
  enable: true
  # Generate both atom and rss2 feeds
  type:
    - atom
    - rss2
  path:
    - feed.xml
    - index.xml
  limit: 30
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:
robotstxt:
  useragent: "*"
  allow:
    - /
  sitemap: https://samirpaul1.github.io/sitemap.xml
all_minifier: false
# pwa:
#   manifest:
#     path: /manifest.json
#     body:
#       name: Samir Paul
#       short_name: SamirPaul
#       icons:
#         - src: /assets/img/favicons/android-chrome-192x192.png
#           sizes: 192x192
#           type: image/png
#         - src: /assets/img/favicons/android-chrome-512x512.png
#           sizes: 512x512
#           type: image/png
#       start_url: /
#       theme_color: '#ffffff'
#       background_color: '#ffffff'
#       display: standalone
#   serviceWorker:
#     path: /sw.js
#     preload:
#       urls:
#         - /
#       posts: 5
#     opts:
#       networkTimeoutSeconds: 20
#     routes:
#       - pattern: !!js/regexp /hm.baidu.com/
#         strategy: networkOnly
#       - pattern: !!js/regexp /www.google-analytics.com/
#         strategy: networkOnly
#       - pattern: !!js/regexp /pagead2.googlesyndication.com/
#         strategy: networkOnly
#       - pattern: !!js/regexp /cdn.jsdelivr.net/
#         strategy: cacheFirst
#       - pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/
#         strategy: cacheFirst
#       - pattern: !!js/regexp /\//
#         strategy: networkFirst
#   priority: 5
deploy:
  type: git
  repo: https://github.com/SamirPaul1/SamirPaul1.github.io
  branch: [main]
  # token: ''
  # message: [message]
  # name: [SamirPaul1]
  # email: [samir.paul.personal@gmail.com]
  # # extend_dirs: [extend directory]
  # ignore_hidden: false # default is true
  # ignore_pattern: regexp