baseURL: "https://samir.pages.dev/" 
title: Samir Paul
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-CP4QE6ZEV0

minify:
    disableXML: true
    minifyOutput: true

languageName: "English"
weight: 1
taxonomies:
  category: categories
  tag: tags
  series: series
menu:
    main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Technical blog made by developer for developers. Computer Science, Data Structures Algorithms, Networking, Artificial Intelligence and Coding Interview Prep."
    author: Samir Paul
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowWordCount: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true
    ShowRssButtonInSectionTermList: true
    hideFooter: false
    ShowToc: true
    TocOpen: false
    hidemeta: false
    comments: false
    images: ["https://spcdn.pages.dev/blog-featured-image-samirpaul-in-blog.webp"]

    profileMode:
        enabled: true
        title: Samir Paul
        subtitle: <a href="#"><img  alt="Welcome" src="/samirpaul-blog-welcome.svg" width="345px" height="29px" loading="lazy" /></a>
        imageUrl: "/avatar.webp"
        imageTitle: Samir Paul
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: About Me
              url: about
            - name: Blog
              url: posts

    socialIcons:
        - name: LinkedIn
          url: "https://linkedin.com/in/SamirPaul"
        - name: GitHub
          url: "https://github.com/SamirPaul1"
        - name: Twitter
          url: "https://twitter.com/SamirPaulb"
        - name: Instagram
          url: "https://www.instagram.com/SamirPaulb"
        - name: Facebook
          url: "https://facebook.com/SamirPaulb"
        - name: Rss
          url: "index.xml"


    editPost:
        URL: "https://twitter.com/intent/follow?screen_name=SamirPaulb"
        Text: "Contact Author" # edit text
        appendFilePath: false # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: "vJAOBxbJTCK2vXG-hLFeGsoC9hXgFlCpuJJ8AcJLROQ"
        bing:
            SiteVerificationTag: "1A92FC2EC113F8616A21D76DA684A133"
        yandex:
            SiteVerificationTag: "fe6a06c57be84984"
        pinterest:
            SiteVerificationTag: "24bac6e1fbf1750de40d59bb788d9dd9"
        norton:
            SiteVerificationTag: "j7w6winrjctu1-mcfpposj35ae-2txdr3qhqt9edmam0gf98j9qtpixft-qv452wjund2cyc9jacd71w81ee6addfggzcmr-affl9b3eblxul7768d9d5dh2fjkupp1h"


    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
        linkFullImages: false
        image: "https://spcdn.pages.dev/blog-featured-image-samirpaul-in-blog.webp"
        alt: "blog-featured-image"
        caption: "Technical blog"

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
